#!/usr/bin/env python3
"""Fit interpretable IRL/Online weighting curves on the latest 365 days.

Uses the frozen historical baseline components already generated by score_baseline_models.py.
No ingestion or prediction-window membership is changed. Primary analysis is cohort-weighted.
The recent-period in-sample winner is reported separately from chronological validation.
"""
from __future__ import annotations

import json
import statistics
from collections import defaultdict
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INFILE = ROOT / "data" / "processed" / "model-results" / "baselines.json"
OUTDIR = ROOT / "data" / "processed" / "last-year-weighting"
RESDIR = ROOT / "results" / "last-year-weighting"

STARTS = [0.70, 0.75, 0.80, 0.85, 0.90, 0.95]
FLOORS = [0.30, 0.40, 0.45, 0.50, 0.55, 0.60]
DECAYS = [0.005, 0.010, 0.015, 0.020]
EPS = 1e-10
HOLDOUT_TRAIN_COHORTS = 6
EXPANDING_MIN_TRAIN_COHORTS = 5


def mean(xs):
    xs = list(xs)
    return statistics.fmean(xs) if xs else None


def pred_map(model):
    return {str(r["key"]): float(r["predicted_pct"]) / 100.0 for r in model.get("prediction", [])}


def actual_map(model):
    return {str(r["key"]): float(r["actual_pct"]) / 100.0 for r in model.get("prediction", [])}


def blend(a, b, w):
    keys = set(a) | set(b)
    out = {k: w * a.get(k, 0.0) + (1.0 - w) * b.get(k, 0.0) for k in keys}
    total = sum(out.values())
    return {k: v / total for k, v in out.items()} if total else {}


def accuracy(pred, actual):
    keys = set(pred) | set(actual)
    return 100.0 * (1.0 - 0.5 * sum(abs(pred.get(k, 0.0) - actual.get(k, 0.0)) for k in keys))


def reconstruct_online(irl, fifty):
    keys = set(irl) | set(fifty)
    raw = {k: 2.0 * fifty.get(k, 0.0) - irl.get(k, 0.0) for k in keys}
    out = {k: (0.0 if -EPS < v < 0.0 else v) for k, v in raw.items()}
    if min(out.values(), default=0.0) < -1e-7:
        raise RuntimeError("Could not reconstruct Online component cleanly from 50/50 prediction")
    out = {k: max(0.0, v) for k, v in out.items()}
    total = sum(out.values())
    return {k: v / total for k, v in out.items()} if total else {}


def weight(days, start, floor, decay):
    return max(floor, min(start, start - decay * days))


def cohort_metric(rows, score_key):
    by = defaultdict(list)
    for r in rows:
        by[r["cohort_id"]].append(r[score_key])
    return mean(mean(v) for v in by.values())


def evaluate(rows, start, floor, decay, include_rows=False):
    scored = []
    for r in rows:
        w = weight(r["days_since_major"], start, floor, decay)
        acc = accuracy(blend(r["irl"], r["online"], w), r["actual"])
        scored.append({**r, "score": acc, "weight": w})
    by = defaultdict(list)
    for r in scored:
        by[r["cohort_id"]].append(r["score"])
    cohort_scores = [mean(v) for v in by.values()]
    out = {
        "start": start,
        "floor": floor,
        "decay_per_day": decay,
        "event_count": len(scored),
        "cohort_count": len(by),
        "mean_event_accuracy": mean(r["score"] for r in scored),
        "mean_cohort_accuracy": mean(cohort_scores),
        "median_cohort_accuracy": statistics.median(cohort_scores) if cohort_scores else None,
    }
    if include_rows:
        out["rows"] = [
            {
                "target_id": r["target_id"],
                "target_name": r["target_name"],
                "date": r["date"],
                "cohort_id": r["cohort_id"],
                "days_since_major": r["days_since_major"],
                "irl_weight": r["weight"],
                "accuracy": r["score"],
            }
            for r in scored
        ]
    return out


def baseline_metric(rows, key):
    return {"event": mean(r[key] for r in rows), "cohort": cohort_metric(rows, key)}


def rank_grid(rows):
    grid = []
    for s in STARTS:
        for f in FLOORS:
            if f > s:
                continue
            for d in DECAYS:
                grid.append(evaluate(rows, s, f, d))
    grid.sort(key=lambda x: (x["mean_cohort_accuracy"], x["mean_event_accuracy"]), reverse=True)
    return grid


def main():
    data = json.loads(INFILE.read_text(encoding="utf-8"))

    # Define "last year" from the latest completed IRL prediction target in the frozen archive,
    # including transition targets for the endpoint even though the blend analysis itself is settled-only.
    eligible_dates = [date.fromisoformat(t["target_start_date"]) for t in data.get("targets", []) if t.get("target_eligible_ge_95")]
    end_date = max(eligible_dates)
    start_date = end_date - timedelta(days=365)

    all_complete = []
    for t in data.get("targets", []):
        if not t.get("target_eligible_ge_95") or t.get("window_class") != "settled":
            continue
        d = date.fromisoformat(t["target_start_date"])
        if not (start_date <= d <= end_date):
            continue
        irl_m = t.get("models", {}).get("irl_only", {})
        half_m = t.get("models", {}).get("fifty_fifty", {})
        current_m = t.get("models", {}).get("current_v2_1", {})
        online_m = t.get("models", {}).get("online_only", {})
        if not (irl_m.get("available") and half_m.get("available") and current_m.get("available") and online_m.get("available")):
            continue
        irl = pred_map(irl_m)
        fifty = pred_map(half_m)
        online = reconstruct_online(irl, fifty)
        actual = actual_map(irl_m)
        all_complete.append({
            "target_id": str(t["target_id"]),
            "target_name": t["target_name"],
            "date": t["target_start_date"],
            "cohort_id": t["cohort_id"],
            "days_since_major": int(t["days_since_major"]),
            "irl": irl,
            "online": online,
            "actual": actual,
            "online_only": float(online_m["field_accuracy_pct"]),
            "irl_only": float(irl_m["field_accuracy_pct"]),
            "fifty": float(half_m["field_accuracy_pct"]),
            "current": float(current_m["field_accuracy_pct"]),
        })

    if not all_complete:
        raise RuntimeError("No recent complete-case settled targets found")

    cohort_dates = {}
    for r in all_complete:
        cohort_dates[r["cohort_id"]] = min(cohort_dates.get(r["cohort_id"], r["date"]), r["date"])
    ordered_cohorts = sorted(cohort_dates, key=lambda c: (cohort_dates[c], c))
    if len(ordered_cohorts) <= HOLDOUT_TRAIN_COHORTS:
        raise RuntimeError("Not enough recent cohorts for fixed holdout")

    grid = rank_grid(all_complete)
    best = grid[0]
    best_detailed = evaluate(all_complete, best["start"], best["floor"], best["decay_per_day"], include_rows=True)

    full_history_winner = evaluate(all_complete, 0.80, 0.55, 0.010)
    current_formula_recalc = evaluate(all_complete, 0.70, 0.30, 0.020)

    train_ids = set(ordered_cohorts[:HOLDOUT_TRAIN_COHORTS])
    holdout_ids = set(ordered_cohorts[HOLDOUT_TRAIN_COHORTS:])
    train = [r for r in all_complete if r["cohort_id"] in train_ids]
    holdout = [r for r in all_complete if r["cohort_id"] in holdout_ids]
    train_grid = rank_grid(train)
    selected = train_grid[0]
    holdout_eval = evaluate(holdout, selected["start"], selected["floor"], selected["decay_per_day"], include_rows=True)

    expanding_rows = []
    for i, cohort in enumerate(ordered_cohorts):
        if i < EXPANDING_MIN_TRAIN_COHORTS:
            continue
        prior_ids = set(ordered_cohorts[:i])
        train_i = [r for r in all_complete if r["cohort_id"] in prior_ids]
        test_i = [r for r in all_complete if r["cohort_id"] == cohort]
        chosen = rank_grid(train_i)[0]
        test_eval = evaluate(test_i, chosen["start"], chosen["floor"], chosen["decay_per_day"])
        expanding_rows.append({
            "cohort_id": cohort,
            "date": cohort_dates[cohort],
            "selected_start": chosen["start"],
            "selected_floor": chosen["floor"],
            "selected_decay_per_day": chosen["decay_per_day"],
            "accuracy": test_eval["mean_cohort_accuracy"],
            "current": mean(r["current"] for r in test_i),
            "fifty": mean(r["fifty"] for r in test_i),
            "irl_only": mean(r["irl_only"] for r in test_i),
        })

    out = {
        "research_question": "Which interpretable IRL/Online decay rule is most accurate on the latest 365 days of archived play?",
        "evidence_window": {"start": start_date.isoformat(), "end": end_date.isoformat()},
        "sample": {
            "event_count": len(all_complete),
            "cohort_count": len(ordered_cohorts),
            "cohorts": [{"cohort_id": c, "date": cohort_dates[c]} for c in ordered_cohorts],
            "selection": ">=95% IRL capture, settled-format, complete IRL/50-50/current/Online components",
        },
        "metric": "Cohort-weighted Field Accuracy; named archetypes only, matching frozen baseline scoring",
        "grid": {"starts": STARTS, "floors": FLOORS, "decays_per_day": DECAYS},
        "baselines": {
            "online_only": baseline_metric(all_complete, "online_only"),
            "irl_only": baseline_metric(all_complete, "irl_only"),
            "fifty_fifty": baseline_metric(all_complete, "fifty"),
            "current_v2_1": baseline_metric(all_complete, "current"),
            "full_history_grid_winner_80_55_1pp": full_history_winner,
            "current_formula_recalculated_70_30_2pp": current_formula_recalc,
        },
        "recent_in_sample": {
            "best_rule": best_detailed,
            "top_20_rules": grid[:20],
            "warning": "Selected and scored on the same 11 recent cohorts; descriptive/in-sample only.",
        },
        "fixed_chronological_holdout": {
            "train_cohorts": ordered_cohorts[:HOLDOUT_TRAIN_COHORTS],
            "test_cohorts": ordered_cohorts[HOLDOUT_TRAIN_COHORTS:],
            "selected_from_training": {k: selected[k] for k in ["start", "floor", "decay_per_day", "mean_cohort_accuracy", "mean_event_accuracy"]},
            "test_selected_rule": holdout_eval,
            "test_baselines": {
                "online_only": baseline_metric(holdout, "online_only"),
                "irl_only": baseline_metric(holdout, "irl_only"),
                "fifty_fifty": baseline_metric(holdout, "fifty"),
                "current_v2_1": baseline_metric(holdout, "current"),
                "full_history_grid_winner_80_55_1pp": evaluate(holdout, 0.80, 0.55, 0.010),
            },
            "warning": "Only five independent holdout cohorts; treat as a directional validation, not a final model selection result.",
        },
        "recent_expanding_walk_forward": {
            "min_training_cohorts": EXPANDING_MIN_TRAIN_COHORTS,
            "tested_cohorts": len(expanding_rows),
            "tuned_rule_mean_accuracy": mean(r["accuracy"] for r in expanding_rows),
            "current_v2_1_mean_accuracy": mean(r["current"] for r in expanding_rows),
            "fifty_fifty_mean_accuracy": mean(r["fifty"] for r in expanding_rows),
            "irl_only_mean_accuracy": mean(r["irl_only"] for r in expanding_rows),
            "rows": expanding_rows,
            "warning": "Very small recent training histories; supplementary to the fixed holdout.",
        },
    }

    OUTDIR.mkdir(parents=True, exist_ok=True)
    RESDIR.mkdir(parents=True, exist_ok=True)
    (OUTDIR / "summary.json").write_text(json.dumps(out, indent=2), encoding="utf-8")

    b = out["baselines"]
    bi = out["recent_in_sample"]["best_rule"]
    h = out["fixed_chronological_holdout"]
    wf = out["recent_expanding_walk_forward"]
    lines = [
        "# Last-year IRL/Online weighting experiment",
        "",
        f"Evidence window: **{start_date.isoformat()} to {end_date.isoformat()}**.",
        f"Complete-case settled sample: **{len(all_complete)} tournaments across {len(ordered_cohorts)} independent cohorts**.",
        "",
        "## Question",
        "",
        "Which interpretable IRL/Online decay rule is most accurate on the latest 365 days of archived play?",
        "",
        "## In-sample recent-period fit",
        "",
        f"Best grid rule: **{bi['start']*100:.0f}% IRL start, {bi['decay_per_day']*100:.1f}pp/day decay, {bi['floor']*100:.0f}% IRL floor**.",
        f"Cohort-weighted accuracy: **{bi['mean_cohort_accuracy']:.2f}%**.",
        "",
        "| Comparator | Cohort accuracy |",
        "|---|---:|",
        f"| Online-only | {b['online_only']['cohort']:.2f}% |",
        f"| IRL-only | {b['irl_only']['cohort']:.2f}% |",
        f"| 50/50 | {b['fifty_fifty']['cohort']:.2f}% |",
        f"| Current v2.1 (70%, -2pp/day, 30% floor) | {b['current_v2_1']['cohort']:.2f}% |",
        f"| Full-history grid winner (80%, -1pp/day, 55% floor) | {b['full_history_grid_winner_80_55_1pp']['mean_cohort_accuracy']:.2f}% |",
        f"| **Recent in-sample winner** | **{bi['mean_cohort_accuracy']:.2f}%** |",
        "",
        "This recent winner is **in-sample** and is not by itself evidence that the rule will predict future events better.",
        "",
        "## Fixed chronological holdout",
        "",
        f"Tune on first {HOLDOUT_TRAIN_COHORTS} recent cohorts; test untouched on final {len(ordered_cohorts)-HOLDOUT_TRAIN_COHORTS} cohorts.",
        f"Training selected: **{h['selected_from_training']['start']*100:.0f}% start, {h['selected_from_training']['decay_per_day']*100:.1f}pp/day, {h['selected_from_training']['floor']*100:.0f}% floor**.",
        f"Holdout selected-rule accuracy: **{h['test_selected_rule']['mean_cohort_accuracy']:.2f}%**.",
        f"Holdout current v2.1: **{h['test_baselines']['current_v2_1']['cohort']:.2f}%**.",
        f"Holdout 50/50: **{h['test_baselines']['fifty_fifty']['cohort']:.2f}%**.",
        f"Holdout IRL-only: **{h['test_baselines']['irl_only']['cohort']:.2f}%**.",
        f"Holdout full-history grid winner: **{h['test_baselines']['full_history_grid_winner_80_55_1pp']['mean_cohort_accuracy']:.2f}%**.",
        "",
        "Only five independent holdout cohorts are available, so this validation is directional rather than decisive.",
        "",
        "## Recent expanding walk-forward (supplementary)",
        "",
        f"After at least {EXPANDING_MIN_TRAIN_COHORTS} recent cohorts, tested {wf['tested_cohorts']} later cohorts.",
        f"Retuned rule: **{wf['tuned_rule_mean_accuracy']:.2f}%**; current v2.1: **{wf['current_v2_1_mean_accuracy']:.2f}%**; 50/50: **{wf['fifty_fifty_mean_accuracy']:.2f}%**; IRL-only: **{wf['irl_only_mean_accuracy']:.2f}%**.",
        "",
        "## Interpretation boundary",
        "",
        "This experiment tests weighting within the existing frozen evidence windows. It does not test the causal hypothesis that increased player numbers or competitiveness caused the recent Online-to-IRL relationship to strengthen, and it does not authorise a production formula change.",
    ]
    (RESDIR / "README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(json.dumps(out, indent=2))


if __name__ == "__main__":
    main()
